baseURL = '/'
title = 'iAssets'
theme = 'pebble'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = true
disableKinds = ['taxonomy', 'term', 'RSS']
enableRobotsTXT = true

[module]
  [module.hugoversion]

  [[module.mounts]]
    source = 'package.json'
    target = 'assets/_jsconfig/package.json'

  [[module.mounts]]
    lang = 'en'
    source = 'content/en'
    target = 'content'

  [[module.mounts]]
    lang = 'zh'
    source = 'content/zh'
    target = 'content'

  [[module.mounts]]
    lang = 'tw'
    source = 'content/tw'
    target = 'content'

  [[module.mounts]]
    lang = 'hk'
    source = 'content/hk'
    target = 'content'

  [[module.mounts]]
    lang = 'mo'
    source = 'content/mo'
    target = 'content'

  [[module.mounts]]
    lang = 'sg'
    source = 'content/sg'
    target = 'content'

  [[module.mounts]]
    lang = 'ja'
    source = 'content/ja'
    target = 'content'

  [[module.mounts]]
    lang = 'ko'
    source = 'content/ko'
    target = 'content'
