baseURL = '/'
title = 'iAssets'
theme = 'pebble'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = true
disableKinds = ['taxonomy', 'term', 'RSS']
enableRobotsTXT = true

[module]
  [module.hugoversion]

  [[module.mounts]]
    source = 'package.json'
    target = 'assets/_jsconfig/package.json'

  [[module.mounts]]
    lang = 'en'
    source = 'content/en'
    target = 'content'

  [[module.mounts]]
    lang = 'zh'
    source = 'content/zh'
    target = 'content'

  [[module.mounts]]
    lang = 'zh-hant'
    source = 'content/zh-hant'
    target = 'content'

  [[module.mounts]]
    lang = 'ja'
    source = 'content/ja'
    target = 'content'

  [[module.mounts]]
    lang = 'ko'
    source = 'content/ko'
    target = 'content'
