[en]
languageName = 'English'
weight = 1

[en.params.pricing]
currency = '$'
yearly = '18'
lifetime = '45'

[zh]
languageName = '中文简体'
weight = 2

[zh.params.pricing]
currency = '¥'
yearly = '128'
lifetime = '328'

[zh-hant]
languageName = '中文繁體'
weight = 3

[zh-hant.params.pricing]
currency = 'NT$'
yearly = '568'
lifetime = '1468'

[ja]
languageName = '日本語'
weight = 4

[ja.params.pricing]
currency = '¥'
yearly = '2680'
lifetime = '6980'

[ko]
languageName = '한국어'
weight = 5

[ko.params.pricing]
currency = '₩'
yearly = '25000'
lifetime = '65000'
