[assets]
  logo = '/assets/local/20260607h41bVQ.png'
  logoAlt = 'iAssets logo'
  brandName = 'iAssets'
  downloadQr = '/assets/local/20260607huIkvB.png'
  version = 'v20261008-activity-mobile'

[theme]
  version = 'v1.0.3'

[contact]
  email = 'idebuginn@gmail.com'

[social]
  wechatQr = '/assets/local/20260607OpjNs1.jpg'
  x = 'https://x.com/xdebuginn'
  telegram = 'https://t.me/tdebuginn'
  xiaohongshu = 'https://www.xiaohongshu.com/user/profile/5d4057fd0000000012007068'
  weibo = 'https://weibo.com/u/7096209693'
  zhihu = 'https://www.zhihu.com/people/debuginn'

[social.icons]
  wechat = '/assets/local/20260607v5H5Ux.svg'
  weibo = '/assets/local/20260607IoieJf.svg'
  xiaohongshu = '/assets/local/20260607S6dw4u.svg'
  zhihu = '/assets/local/20260607dP6b5s.svg'
  x = '/assets/local/20260607TIEZDC.svg'
  telegram = '/assets/local/2026060747C8zB.svg'

[seo]
  defaultSocialTitle = 'iAssets'
  siteURL = ''

[i18n]
  defaultLang = 'en'

[copyright]
  year = 2026
  icp = '鲁ICP备18012789号'
