import fs from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const configPath = path.join(root, "config", "_default", "config.toml");
const languagesPath = path.join(root, "config", "_default", "languages.toml");
const i18nDir = path.join(root, "i18n");
const runtimeDir = path.join(root, "static", "config", "runtime");

function parseTomlScalar(rawValue) {
  const value = rawValue.trim();
  if (value.startsWith("'") && value.endsWith("'")) return value.slice(1, -1);
  if (value.startsWith('"') && value.endsWith('"')) return value.slice(1, -1);
  if (/^-?\d+$/.test(value)) return Number.parseInt(value, 10);
  if (value === "true") return true;
  if (value === "false") return false;
  return value;
}

function parseLanguagesToml(input) {
  const result = {};
  let currentSection = null;

  for (const rawLine of input.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const sectionMatch = line.match(/^\[([^\]]+)\]$/);
    if (sectionMatch) {
      currentSection = sectionMatch[1].split(".");
      continue;
    }

    const kvMatch = rawLine.match(/^\s*([A-Za-z0-9_]+)\s*=\s*(.+?)\s*$/);
    if (!kvMatch) continue;

    const [, key, rawValue] = kvMatch;
    let cursor = result;
    if (currentSection) {
      for (const segment of currentSection) {
        cursor[segment] ||= {};
        cursor = cursor[segment];
      }
    }
    cursor[key] = parseTomlScalar(rawValue);
  }

  return result;
}

function routeToPathKey(route) {
  if (route === "/") return null;
  const match = route.match(/^\/([^/]+)\/$/);
  return match ? match[1] : null;
}

function deriveLangMeta(langKey, defaultLang) {
  const route = langKey === defaultLang ? "/" : `/${langKey}/`;
  if (langKey === "zh") return { appLang: "zh-Hans", route, ogLocale: "zh_CN" };
  if (langKey === "tw") return { appLang: "zh-Hant-TW", route, ogLocale: "zh_TW" };
  if (langKey === "hk") return { appLang: "zh-Hant-HK", route, ogLocale: "zh_HK" };
  if (langKey === "mo") return { appLang: "zh-Hant-MO", route, ogLocale: "zh_MO" };
  if (langKey === "sg") return { appLang: "zh-Hant-SG", route, ogLocale: "zh_SG" };
  if (langKey === "ja") return { appLang: "ja", route, ogLocale: "ja_JP" };
  if (langKey === "ko") return { appLang: "ko", route, ogLocale: "ko_KR" };
  return { appLang: "en", route, ogLocale: "en_US" };
}

function parseFrontMatterToml(raw) {
  const match = raw.match(/^\+\+\+\n([\s\S]*?)\n\+\+\+/);
  if (!match) return {};
  const result = {};
  for (const line of match[1].split(/\r?\n/)) {
    const kvMatch = line.match(/^\s*([A-Za-z0-9_]+)\s*=\s*(.+?)\s*$/);
    if (!kvMatch) continue;
    result[kvMatch[1]] = parseTomlScalar(kvMatch[2]);
  }
  return result;
}

async function readHomeMeta(contentDir) {
  const filePath = path.join(root, contentDir, "_index.md");
  const raw = await fs.readFile(filePath, "utf8");
  return parseFrontMatterToml(raw);
}

async function buildLocaleMaps(languageConfig, defaultLang) {
  const supportedLangs = [];
  const pathLangMap = {};
  const routeMap = {};
  const localeMap = {};
  const keywordsMap = {};
  const pricingMap = {};

  for (const [sectionName, sectionValue] of Object.entries(languageConfig)) {
    const { appLang, route, ogLocale } = deriveLangMeta(sectionName, defaultLang);
    const homeMeta = await readHomeMeta(sectionValue.contentDir);
    const langPricing = (sectionValue.params && sectionValue.params.pricing) || {};

    supportedLangs.push(appLang);
    routeMap[appLang] = route;
    localeMap[appLang] = ogLocale;
    keywordsMap[appLang] = homeMeta.keywords || "";
    pricingMap[appLang] = langPricing;

    const routeKey = routeToPathKey(route);
    if (routeKey) pathLangMap[routeKey] = appLang;

    const languageCode = (sectionValue.languageCode || "").toLowerCase();
    if (languageCode) pathLangMap[languageCode] = appLang;
    pathLangMap[appLang.toLowerCase()] = appLang;
  }

  pathLangMap.zh = "zh-Hans";
  pathLangMap["zh-cn"] = "zh-Hans";
  pathLangMap["zh-hans"] = "zh-Hans";
  pathLangMap["zh-hant"] = "zh-Hant-HK";

  return {
    supportedLangs,
    pathLangMap,
    routeMap,
    localeMap,
    keywordsMap,
    pricing: pricingMap
  };
}

function toJsObjectLiteral(value) {
  return JSON.stringify(value, null, 2);
}

function fileToLang(fileName) {
  return fileName.replace(/\.json$/, "");
}

async function buildCopy(languageConfig, defaultLang) {
  const copy = {};
  for (const [sectionName] of Object.entries(languageConfig)) {
    const { appLang } = deriveLangMeta(sectionName, defaultLang);
    const file = `${sectionName}.json`;
    const raw = JSON.parse(await fs.readFile(path.join(i18nDir, file), "utf8"));
    const flat = {};
    for (const [key, value] of Object.entries(raw)) {
      flat[key] = typeof value === "object" && value && "other" in value ? value.other : value;
    }
    copy[appLang] = flat;
  }

  const source = `// Generated by scripts/build-runtime.mjs. Do not edit directly.\nexport const COPY = ${toJsObjectLiteral(copy)};\n`;
  await fs.writeFile(path.join(runtimeDir, "copy.js"), source);
}

async function buildLocales() {
  const rootConfig = parseLanguagesToml(await fs.readFile(configPath, "utf8"));
  const languageConfig = parseLanguagesToml(await fs.readFile(languagesPath, "utf8"));
  const maps = await buildLocaleMaps(languageConfig, rootConfig.defaultContentLanguage);

  const source = `// Generated by scripts/build-runtime.mjs. Do not edit directly.\n` +
    `export const SUPPORTED_LANGS = ${JSON.stringify(maps.supportedLangs)};\n\n` +
    `export const PATH_LANG_MAP = ${toJsObjectLiteral(maps.pathLangMap)};\n\n` +
    `export const LANG_ROUTE_MAP = ${toJsObjectLiteral(maps.routeMap)};\n\n` +
    `export const LANG_LOCALE_MAP = ${toJsObjectLiteral(maps.localeMap)};\n\n` +
    `export const LANG_META_KEYWORDS = ${toJsObjectLiteral(maps.keywordsMap)};\n\n` +
    `export const PRICE_BY_LANG = ${toJsObjectLiteral(maps.pricing)};\n`;

  await fs.writeFile(path.join(runtimeDir, "locales.js"), source);
  await buildCopy(languageConfig, rootConfig.defaultContentLanguage);
}

await fs.mkdir(runtimeDir, { recursive: true });
await buildLocales();
